dataset: 'amass'
t_his: 30
t_pred: 120
batch_size: 64
num_epoch: 3001
num_data_sample: 50000
num_val_data_sample: 5000
lr: 3.e-4
n_pre: 20
padding: 'LastFrame'
Complete: True
noise_steps: 1000
ddim_timesteps: 100
scheduler: 'Cosine' # 'Cosine' 'Linear' 'Sqrt' 'Sigmoid'
num_layers: 13
num_heads: 8
latent_dims: 512
dropout: 0.2
mod_train: 0.8
mod_test: 1.0
dct_norm_enable: False
multimodal_threshold: 0.4
seed: 6
